---
title: "CV"
author: "Chetan Chawla"
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  html_document:
    df_print: paged
  word_document: default
geometry: margin=1in
jobtitle: Associate Professor of Entrepreneurship, School of Business and Entrepreneurship
address: North Central College · 30 North Brainard Street · Naperville, IL 60540, USA
fontawesome: yes
email: chetanchawla@gmail.com
twitter: chetanchawla
linkedin: chetanchawla  
web: chetanchawla.com
github: csqr
keywords: R Markdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue

---

# Career Summary

I am a teacher, researcher, and consultant of business strategy, and entrepreneurship. I have 10+ years of business consulting experience with clients ranging from Fortune 100 defense companies to Indian retailers, and technology startups. 

My academic research focus is the association between capital providers (debt, equity, and non-traditional forms of financing e.g. crowdfunding) and startup outcomes. More specifically, I investigate the capital provider and startup linkage in contexts ranging from S & P 500 companies to cryptocurrency, blockchain projects, and other early-stage ventures. 

My academic teaching focus is strategy, and entrepreneurship.

I am a tenured Associate Professor of Entrepreneurship at North Central College in Naperville, IL in the School of Business and Entrepreneurship.

# Academic work experience

[*North Central College*](https://www.northcentralcollege.edu/) \hfill Naperville, IL

[Associate Professor of Entrepreneurship](https://www.northcentralcollege.edu/profile/cchawla) \hfill 2021-

Assistant Professor of Entrepreneurship \hfill 2015-2021

>Primary teaching responsibilities in entrepreneurship (undergraduate lean validation class), and strategy (undergraduate, and MBA strategy capstone classes).  

>Teaching ratings $\geq$ 4.4 out of 5, in both undergraduate, and graduate courses. 

>Research focus: entrepreneurial financing, and other outcomes in the context of blockchains, and cryptocurrencies.

>Institutional service: Election Committee, Scholarship and Research Committee, entrepreneurship curriculum redesign, and assessment for AACSB accreditation.

# Education

[*Isenberg School of Management, University of Massachusetts*](https://www.isenberg.umass.edu/) \hfill Amherst, MA

Ph.D. in Strategic Management \hfill 2009 – 2015

>Research focus: capital structure, innovation, behavioral theory, corporate governance.                         

>Professional Association Membership: Academy of Management (divisions: Strategic Management, Entrepreneurship, Organizational and Management Theory, Technology and Innovation Management, and Research Methods).  

>Strategic Management Society (Interest Groups: Entrepreneurship & Strategy, and Behavioral Strategy).

[*Marshall School of Business, University of Southern California*](https://www.marshall.usc.edu/) \hfill Los Angeles, CA

M.B.A. in International Business \hfill 2007 – 2008

>Finalist – Annual Technology Commercialization Competition (Lloyd Greif Center for Entrepreneurial Studies), 2008

[*Sri Aurobindo College, University of Delhi*](http://www.aurobindo.du.ac.in/) \hfill New Delhi, India

Bachelor of Arts (Honors) in English \hfill 2003

>Represented India in Youth Across the Commonwealth (YAC) – Canada & Jamaica – 2001.    

>Certificate in Enterprise Management from the Dept. of Management Studies, Indian Institute of Technology (I.I.T.) Delhi in 2005.


# Publications

## Peer-reviewed journal publications

Chawla, C. 2020. "[Trust in blockchains: Algorithmic and organizational](https://doi.org/10.1016/j.jbvi.2020.e00203)." *Journal of Business Venturing Insights*, 14.  

Branch, B. S., Sharma, A., Chawla, C., & Tu, F. 2014. "[An Updated Model of Price-to-Book](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2682606)." *Journal of Applied Finance (Formerly Financial Practice and Education)*, 24(1). 

Sharma, A., Branch, B. S., Chawla, C., & Qiu, L. 2013. "[Explaining Market to Book: The Relative Impact of Firm Performance, Growth, and Risk](http://www.westga.edu/~bquest/2013/MarketToBook2013.pdf)." *Business Quest*, 277-293. 

Chawla, C., Mangaliso, M., Knipes, B., & Gauthier, J. 2012. "[Antecedents and implications of uncertainty in management: A historical perspective](https://doi.org/10.1108/17511341211206852)." *Journal of Management History*, 18(2), 200-218. 

## Peer-reviewed case studies

Chawla, C. 2021. "[Financing a New Type of Grill](https://sk.sagepub.com/cases/financing-a-new-kind-of-portable-grill)." *SAGE Business Cases*.  

Chawla, C. & Jones, T. 2021. "[Launching a Venture during a Pandemic: SLAB Outdoors LLC](https://sk.sagepub.com/cases/launching-a-venture-during-a-pandemic-slab-outdoors-llc)." *SAGE Business Cases*.

## Conference proceedings

Chawla, C. 2019. "[The Categorical Conundrum: Legitimacy in Flux and Interpretive Uncertainty during Category Emergence](https://journals.aom.org/doi/abs/10.5465/AMBPP.2019.17513abstract)." *Proceedings of the Academy of Management Annual Conference, Boston*.

Chawla, C. & Tinoco, E. 2018. "[Capital Structure Heterogeneity and Firm Strategic Actions: a Transaction Cost Lens](https://journals.aom.org/doi/abs/10.5465/AMBPP.2018.16626abstract)." *Proceedings of the Academy of Management Annual Conference, Chicago*.

Chawla, C. & Sharma, A. 2016. "[Conflicting Voices & Strategic Choices:Capital Provider Time Horizon And Mergers & Acquisitions](https://journals.aom.org/doi/10.5465/ambpp.2016.14704abstract)." *Proceedings of the Academy of Management Annual Conference, Anaheim*.

## Conference presentations

Chawla, C. 2019. "The Categorical Conundrum: Legitimacy in Flux and Interpretive Uncertainty during Category Emergence." *Academy of Management Annual Conference, Boston*.

Chawla, C. 2019. "The Emergence of Technology Frames in Blockchain Projects: Adversarial Governance of Obscure Stakeholders." *Strategic Management Society Annual Conference, Minneapolis*.

Chawla, C. & Tinoco, E. 2018. "Capital Structure Heterogeneity and Firm Strategic Actions: a Transaction Cost Lens." *Academy of Management Annual Conference, Chicago*.

Chawla, C. & Sharma, A. 2016. "Conflicting Voices & Strategic Choices:Capital Provider Time Horizon And Mergers & Acquisitions." *Academy of Management Annual Conference, Anaheim*.

Chawla, C. & Sharma, A. 2013. "Indebtedness of Equity: The Unsung Role of Debt in Indian Risk Taking." *Strategic Management Society Special Conference, Mohali, India*.

Chawla, C. 2013. "Exploring the Antecedents of Consumer Participation in Value Co-Creation: Microfoundations of Demand-Side Strategy." *European Group for Organizational Studies 29th Annual Colloquium, Montreal, Canada*.

Chawla, C. 2011. "Participated in Track 1 (pre-proposal) of the selective Doctoral Consortium." *West Coast Research Symposium on Technology Entrepreneurship, University of Washington, Seattle*.

Branch, B., Sharma, A, Chawla, C., Qiu, L. 2011. ". Mergers & Acquisitions and the Universal Investor." *Decision Sciences Institute Annual Meeting, Boston*.

Chawla, C. 2011. "Unweaving the Web: Value Co-creation as Strategy" *Theorizing the Web Conference, University of Maryland*.

Chawla, C., Mangaliso, M, Knipes, B., Gauthier, J. 2010. "Antecedents & Implications of Uncertainty in Management: A Historical Perspective." *Academy of Management Annual Conference, Montreal*.

# Awards and grants

Academy of Management Annual Meeting 2010 Best Paper Award: CEBC Halloran Prize in the History of Corporate Responsibility. 
Paper: Chawla, C., Mangaliso, M, Knipes, B., Gauthier, J. 2010. "Antecedents & Implications of Uncertainty in Management: A Historical Perspective."  

2011-2012 Isenberg Scholar Award ($10,000) for integrating engineering & business research.

[Investor Responsibility Research Center Institute](http://www.irrcinstitute.org/) research grant 2010-2012.
Research Assistant for team that won [IRRCI grant for research on universal investors and M & A](https://www.weinberg.udel.edu/irrci/research/858). Principal Investigators: Dr. Anurag Sharma & Dr. Ben Branch.

Summer Research Grants Won: 2016 ($2500), 2017 ($3000), 2019 ($2250), 2021 ($2100) from North Central College.

# Working papers/ under review

Chawla, C. 2021. "NFTs as Real Options."  *Under review*.

Chawla, C. 2021. "Entrepreneurial Finance on the Blockchain: Rethinking Agency Theory." *Paper in analysis stage*.

Chawla, C. 2021. "Blockchain Platforms." *Working title, paper in research design stage*.

# Professional service as reviewer

Ad hoc reviewer [The Academy of Management Review](https://aom.org/research/journals/review). 

Ad hoc reviewer [Journal of Business Research](https://www.journals.elsevier.com/journal-of-business-research).

Ad hoc reviewer [Academy of Management Annual Conference](https://aom.org/events/annual-meeting).

# Non-academic work experience

*Date My Wardrobe * \hfill Boston, MA & Amsterdam

Strategy Advisor \hfill 2013-2015

>Fashion technology startup based in Babson College’s Butler Venture Accelerator. 

>[Beta launch in November 2014 in Boston, and Amsterdam](https://www.bizjournals.com/boston/blog/startups/2014/09/babson-college-spinout-date-my-wardrobe-debuts.html).  

>Finalist (top 3 out of 35 startups) in Lean Startup Challenge Boston Fall 2013. 

>Y Combinator Female Founders Conference participant in March 2014. 

>Y Combinator Startup School Fall 2014 participant.

>Shut down in 2015 due to adverse unit economics. 


[*Lockheed Martin Corporation – Mission Systems* ](https://www.lockheedmartin.com/en-us/who-we-are/business-areas/rotary-and-mission-systems.html) \hfill Los Angeles & Italy 

Consultant \hfill 2008

>Leveraged strong analytical, strategic, and market research capabilities to empower client to take advantage of global consolidation in the Defense and Homeland Security software sector. Part of team of four consultants responsible for identifying, evaluating, and initiating technology partnerships/acquisitions in Italy based on extensive in-market research. Enhanced competitive position in Europe.

>Strategic evaluation of software product/ technology portfolio of potential partners – Technology Readiness Level.

>In depth country (Italy) research of companies in four technology areas – Web services (logistics and transportation software on SOA platform), Geospatial Information Systems (including open source GRASS), Search & Discovery (reconnaissance, and surveillance), and Knowledge Management.

>Analysis of cultural/ technological fit based on primary (interviews and market research in Italy), and secondary research (scientific papers, industry white papers etc.).

>Due diligence of legal, organizational, and regulatory factors affecting potential partnership (offset trade requirements, technology transfer regulation etc.).

>M & A due diligence (financial analysis) of over two dozen Italian software firms. Initiation of partnership discussions with C-level executives.

>Developed scenario analysis, and strategy plans for senior executives.

>Result: 1 acquisiton and 1 technology partnership.

# References

Available upon request. 